-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DimCustomer"
(
    customerid integer NOT NULL,
    category "char" NOT NULL,
    country "char" NOT NULL,
    industry "char" NOT NULL,
    CONSTRAINT "DimCustomer_pkey" PRIMARY KEY (customerid)
);

CREATE TABLE IF NOT EXISTS public."DimMonth"
(
    monthid integer NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    monthname "char" NOT NULL,
    quarter integer NOT NULL,
    quartername "char" NOT NULL,
    CONSTRAINT "DimMonth_pkey" PRIMARY KEY (monthid)
);

CREATE TABLE IF NOT EXISTS public."FactBilling"
(
    rowid integer NOT NULL,
    customerid integer NOT NULL,
    monthid integer NOT NULL,
    billedamount integer NOT NULL,
    CONSTRAINT "FactBilling_pkey" PRIMARY KEY (rowid)
);

CREATE TABLE IF NOT EXISTS public."FactSales"
(
    rowid interval NOT NULL,
    storeid integer NOT NULL,
    dateid integer NOT NULL,
    totalsales numeric NOT NULL,
    PRIMARY KEY (rowid)
);

CREATE TABLE IF NOT EXISTS public."DimStore"
(
    storeid integer NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    PRIMARY KEY (storeid)
);

CREATE TABLE IF NOT EXISTS public."DimDate"
(
    dateid integer NOT NULL,
    day date NOT NULL,
    weekday integer NOT NULL,
    weekdayname character varying NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    monthname character varying NOT NULL,
    quarter integer NOT NULL,
    quartername character varying NOT NULL,
    PRIMARY KEY (dateid)
);

ALTER TABLE IF EXISTS public."FactBilling"
    ADD CONSTRAINT "FactBilling_customerid_fkey" FOREIGN KEY (customerid)
    REFERENCES public."DimCustomer" (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactBilling"
    ADD CONSTRAINT "FactBilling_monthid_fkey" FOREIGN KEY (monthid)
    REFERENCES public."DimMonth" (monthid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (storeid)
    REFERENCES public."DimStore" (storeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."DimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;